### PR TITLE
enhanced ReadMe to explain how to add both Java and Android plugins

### PR DESCRIPTION
**Pull request by digital-ember**

### CODE REVIEW

**Comment by StefMa** [comment]
Thanks for the PR!
The readme is also updated with #71.
I hope that makes everything a little bit clearer and we don't need to show examples for both extensions...

**Comment by passsy** [comment]
@StefMa I think this PR here is better. I miss `javaArtifact` not beeing mentioned in the `README.md`

**Comment by StefMa** [comment]
There is a whole new section about the extension:
https://github.com/StefMa/AndroidArtifacts#extension-name

**Comment by passsy** [comment]
nobody reads the text. I prefer two short samples.

java module -> do this

android module -> do this

**Pull request closed without merging**
